version: "3.7"
services:
  db:
    image: redis
    user: root
    command: --appendonly yes

  api-server:
    build:
      context: ./
      target: api-server
    image: ${DOCKER_REGISTRY:-dccn}/filer-gateway-api:${DOCKER_IMAGE_TAG:-latest}
    user: root
    volumes:
      - ${HOME_VOL-/home}:/home:ro
      - ${PROJECT_VOL:-/project}:/project:ro
      - ${PROJECT_FREENAS_VOL:-/project_freenas}:/project_freenas:ro
      - ${PROJECT_CEPHFS_VOL:-/project_cephfs}:/project_cephfs:ro
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    depends_on:
      - db
    command: -p 8080 -v -r db:6379

  worker:
    build:
      context: ./
      target: worker
    image: ${DOCKER_REGISTRY:-dccn}/filer-gateway-worker:${DOCKER_IMAGE_TAG:-latest}
    user: root
    privileged: true
    volumes:
      - ${HOME_VOL-/home}:/home:rw
      - ${PROJECT_VOL:-/project}:/project:rw
      - ${PROJECT_FREENAS_VOL:-/project_freenas}:/project_freenas:rw
      - ${PROJECT_CEPHFS_VOL:-/project_cephfs}:/project_cephfs:rw
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    depends_on:
      - db
      - api-server
    command: -v -r db:6379
