version: "3.7"
services:
  api-server:
    ports:
      - ${FILER_GATEWAY_EXTERNAL_PORT:-8080}:8080
    networks:
      default:
      proxynet:
        aliases:
          - filer-gateway

networks:
  proxynet:
    external: true
