version: "3.7"
services:
  db:
    volumes:
      - ${VOL_DB_DATA:-/mnt/docker/data/filer-gateway/db}:/data
    networks:
      default:

networks:
  default:
    attachable: true
  proxynet:
    external: true
