version: "3.7"
services:
  filer-gateway:
    build:
      context: ./
    image: ${DOCKER_REGISTRY:-dccn}/filer-gateway:${DOCKER_IMAGE_TAG:-latest}
    user: root
    volumes:
      - ${HOME_VOL-/home}:/home:ro
      - ${PROJECT_VOL:-/project}:/project:ro
      - ${PROJECT_FREENAS_VOL:-/project_freenas}:/project_freenas:ro
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    command: -p 8080 -v
