apiKey: demo
auth:
  demo: demo123
jwksEndpoint: https://auth-dev.dccn.nl/.well-known/openid-configuration/jwks 
netapp:
  projectRoot: /project
freenas:
  projectRoot: /project_freenas
cephfs:
  projectRoot: /project_cephfs