netapp:
  apiURL: https://131.174.44.94
  apiUser: gatewayadmin
  apiPass:
  projectRoot: /project
  projectUID: 1010
  projectGID: 1010
  projectMode: "volume"
  vserver: "atreides"
  exportPolicyHome: "dccn-home-nfs-vpn"
  exportPolicyProject: "dccn-projects"

freenas:
  apiURL: https://freenas.dccn.nl/api/v2.0
  apiUser: root
  apiPass:
  projectRoot: /project_freenas
  projectUser: project
  projectGroup: project_g
  zfsDatasetPrefix: zpool001/project

cephfs:
  projectRoot: /project_cephfs
  projectUser: project
  projectGroup: project_g
